// IMPORTANT: StateNotifierProvider is deprecated in Riverpod 2.x and
// moved to legacy.dart in Riverpod 3.0. This file uses the modern
// NotifierProvider API with riverpod_annotation for code generation.
//
// After adding dependencies, run:
//   flutter pub run build_runner build --delete-conflicting-outputs
//
// This generates: workout_provider.freezed.dart  (from freezed)
//                 workout_provider.g.dart          (from riverpod_generator)

import 'dart:async';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'workout_provider.freezed.dart';
part 'workout_provider.g.dart';

// ── State ─────────────────────────────────────────────────────────────────────

/// Immutable state for an active workout session.
///
/// [currentExercise] — name of the exercise currently on screen
/// [timeLeft]        — seconds remaining in the current exercise interval
/// [isPaused]        — whether the countdown is paused
/// [isCompleted]     — true when timeLeft hits 0 and the set is finished
@freezed
abstract class WorkoutState with _$WorkoutState {
  const factory WorkoutState({
    @Default('') String currentExercise,
    @Default(0)  int    timeLeft,
    @Default(false) bool isPaused,
    @Default(false) bool isCompleted,
  }) = _WorkoutState;
}

// ── Notifier ──────────────────────────────────────────────────────────────────

/// [WorkoutNotifier] drives the workout countdown timer.
///
/// The provider is auto-generated by riverpod_generator as [workoutNotifierProvider].
///
/// Usage in a widget:
/// ```dart
/// final state = ref.watch(workoutNotifierProvider);
/// ref.read(workoutNotifierProvider.notifier).startExercise('Push-ups', 30);
/// ```
@riverpod
class WorkoutNotifier extends _$WorkoutNotifier {

  Timer? _timer;

  @override
  WorkoutState build() {
    // Cancel the timer when the provider is disposed (e.g. leaving the screen)
    ref.onDispose(() {
      _timer?.cancel();
    });

    return const WorkoutState();
  }

  // ── Public API ─────────────────────────────────────────────────────────────

  /// Start a new exercise interval.
  /// Cancels any running timer before starting a new one.
  void startExercise(String exercise, int durationSeconds) {
    assert(durationSeconds > 0, 'durationSeconds must be > 0');
    _timer?.cancel();

    state = WorkoutState(
      currentExercise: exercise,
      timeLeft: durationSeconds,
      isPaused: false,
      isCompleted: false,
    );

    _startTicking();
  }

  /// Toggle pause / resume.
  void togglePause() {
    if (state.isCompleted) return;

    if (state.isPaused) {
      state = state.copyWith(isPaused: false);
      _startTicking();
    } else {
      _timer?.cancel();
      state = state.copyWith(isPaused: true);
    }
  }

  /// Manually advance one tick (useful for testing or skip-ahead).
  void tick() {
    if (state.isPaused || state.isCompleted || state.timeLeft <= 0) return;
    _applyTick();
  }

  /// Reset the current exercise without starting a new one.
  void reset() {
    _timer?.cancel();
    state = const WorkoutState();
  }

  // ── Private helpers ────────────────────────────────────────────────────────

  void _startTicking() {
    _timer = Timer.periodic(const Duration(seconds: 1), (_) => _applyTick());
  }

  void _applyTick() {
    if (state.timeLeft <= 1) {
      _timer?.cancel();
      state = state.copyWith(timeLeft: 0, isCompleted: true);
    } else {
      state = state.copyWith(timeLeft: state.timeLeft - 1);
    }
  }
}
