// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'workout_provider.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

String _$workoutNotifierHash() => r'a61189df082ed758abd25d64af1ee757ef970355';

/// [WorkoutNotifier] drives the workout countdown timer.
///
/// The provider is auto-generated by riverpod_generator as [workoutNotifierProvider].
///
/// Usage in a widget:
/// ```dart
/// final state = ref.watch(workoutNotifierProvider);
/// ref.read(workoutNotifierProvider.notifier).startExercise('Push-ups', 30);
/// ```
///
/// Copied from [WorkoutNotifier].
@ProviderFor(WorkoutNotifier)
final workoutNotifierProvider =
    AutoDisposeNotifierProvider<WorkoutNotifier, WorkoutState>.internal(
  WorkoutNotifier.new,
  name: r'workoutNotifierProvider',
  debugGetCreateSourceHash: const bool.fromEnvironment('dart.vm.product')
      ? null
      : _$workoutNotifierHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef _$WorkoutNotifier = AutoDisposeNotifier<WorkoutState>;
// ignore_for_file: type=lint
// ignore_for_file: subtype_of_sealed_class, invalid_use_of_internal_member, invalid_use_of_visible_for_testing_member, deprecated_member_use_from_same_package
