import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/theme/app_theme.dart';
import 'features/dashboard/screens/dashboard_screen.dart';

/// FitBuddy — entry point.
///
/// Firebase: google-services.json / GoogleService-Info.plist are required
/// for auth, FCM and the SOS WebSocket.  When those files are not present
/// (local development / UI testing), Firebase.initializeApp() is skipped
/// and all features that don't touch Firebase work normally.
///
/// TODO: uncomment Firebase init once platform config files are added:
///
///   import 'package:firebase_core/firebase_core.dart';
///   import 'firebase_options.dart';   // generated by FlutterFire CLI
///
///   await Firebase.initializeApp(
///     options: DefaultFirebaseOptions.currentPlatform,
///   );
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(
    // ProviderScope is the Riverpod state container for the entire app.
    // All providers are lazily created on first access within this scope.
    const ProviderScope(
      child: FitBuddyApp(),
    ),
  );
}

class FitBuddyApp extends StatelessWidget {
  const FitBuddyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title:        'FitBuddy',
      debugShowCheckedModeBanner: false,
      theme:        AppTheme.light,
      darkTheme:    AppTheme.dark,
      // Dark mode first — matches Electric Lime design direction.
      themeMode:    ThemeMode.dark,
      // DashboardScreen is the root shell (NavigationBar + tab switcher).
      // Pantry tab is fully functional — tap the kitchen icon to test it.
      home:         const DashboardScreen(),
    );
  }
}
